### PR TITLE
Make left/right_idelems give Set, split up CN functions, use allequal, misc style

### PR DESCRIPTION
**Pull request by devinallen**
As discussed on HoJ

### CODE REVIEW

**Review by jakobjpeters — CHANGES_REQUESTED** [review]
Everything looks great, except that the left and right identity functions need to be reverted to their original names.

**Comment by devinallen** [comment]
hmmm, i feel like we already have `identity` as a function which takes anything and returns it (i.e. operator -> operator), and you would expect `left_identity` and `right_identity` to do something similar (but they do operator -> set of nullary operators). I'm not set on `left_idelems`, but I think we could find a better name than the current one. Something which indicates that it returns a set of values, and that those values are pretty much truth values? maybe a less abbreviated term like `left_identity_elements`?

**Comment by jakobjpeters** [comment]
Hmmm they're very related conceptually, but you are right in that the return values are different. What do you think about `*_neutrals`? That provides more distinction from `identity`, better describes the return value, and isn't *too* long.

**Comment by devinallen** [comment]
I like that, how's this?

**Pull request merged**
